- name: "[control] Download kubectl"
  get_url:
    url: https://storage.googleapis.com/kubernetes-release/release/v1.0.1/bin/linux/amd64/kubectl
    dest: /home/core/bin/kubectl_
    mode: 0555
  tags: deis-control

- name: "[control] Setup kubectl wrapper"
  copy:
    src: kubectl-wrapper
    dest: /home/core/bin/kubectl
    owner: core
    mode: 0555
  tags: deis-control

- stat: path=/home/core/.bashrc
  register: bashrc_stat
  tags: deis-control

- command: unlink /home/core/.bashrc
  when: not bashrc_stat.stat.exists or bashrc_stat.stat.islnk
  ignore_errors: true
  tags: deis-control

- name: "[control] Custom .bashrc for core user"
  copy:
    src: bashrc
    dest: /home/core/.bashrc
    owner: core
    mode: 0777
  tags: deis-control

- name: "[control] Set ~/bin to PATH"
  lineinfile:
    dest: /home/core/.bashrc
    line: "export PATH=$PATH:/home/core/bin/"
  tags: deis-control
